package com.deal.mrzhang.deal.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table first_question_type
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class FirstQuestionType implements Serializable {
    /**
     * Database Column Remarks:
     *   一级问题类型id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column first_question_type.question_type_id
     *
     * @mbg.generated
     */
    private Integer questionTypeId;

    /**
     * Database Column Remarks:
     *   一级问题类型名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column first_question_type.question_type_name
     *
     * @mbg.generated
     */
    private String questionTypeName;

    /**
     * Database Column Remarks:
     *   问题类型id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column first_question_type.type_id
     *
     * @mbg.generated
     */
    private Integer typeId;

    /**
     * Database Column Remarks:
     *   问题类型名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column first_question_type.type_name
     *
     * @mbg.generated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table first_question_type
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column first_question_type.question_type_id
     *
     * @return the value of first_question_type.question_type_id
     *
     * @mbg.generated
     */
    public Integer getQuestionTypeId() {
        return questionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column first_question_type.question_type_id
     *
     * @param questionTypeId the value for first_question_type.question_type_id
     *
     * @mbg.generated
     */
    public void setQuestionTypeId(Integer questionTypeId) {
        this.questionTypeId = questionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column first_question_type.question_type_name
     *
     * @return the value of first_question_type.question_type_name
     *
     * @mbg.generated
     */
    public String getQuestionTypeName() {
        return questionTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column first_question_type.question_type_name
     *
     * @param questionTypeName the value for first_question_type.question_type_name
     *
     * @mbg.generated
     */
    public void setQuestionTypeName(String questionTypeName) {
        this.questionTypeName = questionTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column first_question_type.type_id
     *
     * @return the value of first_question_type.type_id
     *
     * @mbg.generated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column first_question_type.type_id
     *
     * @param typeId the value for first_question_type.type_id
     *
     * @mbg.generated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column first_question_type.type_name
     *
     * @return the value of first_question_type.type_name
     *
     * @mbg.generated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column first_question_type.type_name
     *
     * @param typeName the value for first_question_type.type_name
     *
     * @mbg.generated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
}