package com.deal.mrzhang.deal.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table question_type_aggr
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class QuestionTypeAggr implements Serializable {
    /**
     * Database Column Remarks:
     *   问题类型统计分析表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_type_aggr.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   问题类型一级id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_type_aggr.question_type_id
     *
     * @mbg.generated
     */
    private Integer questionTypeId;

    /**
     * Database Column Remarks:
     *   问题类型一级名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_type_aggr.question_type_name
     *
     * @mbg.generated
     */
    private String questionTypeName;

    /**
     * Database Column Remarks:
     *   问题创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_type_aggr.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question_type_aggr
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_type_aggr.id
     *
     * @return the value of question_type_aggr.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_type_aggr.id
     *
     * @param id the value for question_type_aggr.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_type_aggr.question_type_id
     *
     * @return the value of question_type_aggr.question_type_id
     *
     * @mbg.generated
     */
    public Integer getQuestionTypeId() {
        return questionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_type_aggr.question_type_id
     *
     * @param questionTypeId the value for question_type_aggr.question_type_id
     *
     * @mbg.generated
     */
    public void setQuestionTypeId(Integer questionTypeId) {
        this.questionTypeId = questionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_type_aggr.question_type_name
     *
     * @return the value of question_type_aggr.question_type_name
     *
     * @mbg.generated
     */
    public String getQuestionTypeName() {
        return questionTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_type_aggr.question_type_name
     *
     * @param questionTypeName the value for question_type_aggr.question_type_name
     *
     * @mbg.generated
     */
    public void setQuestionTypeName(String questionTypeName) {
        this.questionTypeName = questionTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_type_aggr.create_date
     *
     * @return the value of question_type_aggr.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_type_aggr.create_date
     *
     * @param createDate the value for question_type_aggr.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}