package com.deal.mrzhang.deal.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class QuestionDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question_detail
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question_detail
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question_detail
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbg.generated
     */
    public QuestionDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table question_detail
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDescsIsNull() {
            addCriterion("descs is null");
            return (Criteria) this;
        }

        public Criteria andDescsIsNotNull() {
            addCriterion("descs is not null");
            return (Criteria) this;
        }

        public Criteria andDescsEqualTo(String value) {
            addCriterion("descs =", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsNotEqualTo(String value) {
            addCriterion("descs <>", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsGreaterThan(String value) {
            addCriterion("descs >", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsGreaterThanOrEqualTo(String value) {
            addCriterion("descs >=", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsLessThan(String value) {
            addCriterion("descs <", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsLessThanOrEqualTo(String value) {
            addCriterion("descs <=", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsLike(String value) {
            addCriterion("descs like", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsNotLike(String value) {
            addCriterion("descs not like", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsIn(List<String> values) {
            addCriterion("descs in", values, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsNotIn(List<String> values) {
            addCriterion("descs not in", values, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsBetween(String value1, String value2) {
            addCriterion("descs between", value1, value2, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsNotBetween(String value1, String value2) {
            addCriterion("descs not between", value1, value2, "descs");
            return (Criteria) this;
        }

        public Criteria andSolutionIsNull() {
            addCriterion("solution is null");
            return (Criteria) this;
        }

        public Criteria andSolutionIsNotNull() {
            addCriterion("solution is not null");
            return (Criteria) this;
        }

        public Criteria andSolutionEqualTo(String value) {
            addCriterion("solution =", value, "solution");
            return (Criteria) this;
        }

        public Criteria andSolutionNotEqualTo(String value) {
            addCriterion("solution <>", value, "solution");
            return (Criteria) this;
        }

        public Criteria andSolutionGreaterThan(String value) {
            addCriterion("solution >", value, "solution");
            return (Criteria) this;
        }

        public Criteria andSolutionGreaterThanOrEqualTo(String value) {
            addCriterion("solution >=", value, "solution");
            return (Criteria) this;
        }

        public Criteria andSolutionLessThan(String value) {
            addCriterion("solution <", value, "solution");
            return (Criteria) this;
        }

        public Criteria andSolutionLessThanOrEqualTo(String value) {
            addCriterion("solution <=", value, "solution");
            return (Criteria) this;
        }

        public Criteria andSolutionLike(String value) {
            addCriterion("solution like", value, "solution");
            return (Criteria) this;
        }

        public Criteria andSolutionNotLike(String value) {
            addCriterion("solution not like", value, "solution");
            return (Criteria) this;
        }

        public Criteria andSolutionIn(List<String> values) {
            addCriterion("solution in", values, "solution");
            return (Criteria) this;
        }

        public Criteria andSolutionNotIn(List<String> values) {
            addCriterion("solution not in", values, "solution");
            return (Criteria) this;
        }

        public Criteria andSolutionBetween(String value1, String value2) {
            addCriterion("solution between", value1, value2, "solution");
            return (Criteria) this;
        }

        public Criteria andSolutionNotBetween(String value1, String value2) {
            addCriterion("solution not between", value1, value2, "solution");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterionForJDBCDate("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterionForJDBCDate("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterionForJDBCDate("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterionForJDBCDate("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("create_time like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("create_time not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andTypeIdIsNull() {
            addCriterion("type_id is null");
            return (Criteria) this;
        }

        public Criteria andTypeIdIsNotNull() {
            addCriterion("type_id is not null");
            return (Criteria) this;
        }

        public Criteria andTypeIdEqualTo(Integer value) {
            addCriterion("type_id =", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotEqualTo(Integer value) {
            addCriterion("type_id <>", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdGreaterThan(Integer value) {
            addCriterion("type_id >", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("type_id >=", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLessThan(Integer value) {
            addCriterion("type_id <", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("type_id <=", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdIn(List<Integer> values) {
            addCriterion("type_id in", values, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotIn(List<Integer> values) {
            addCriterion("type_id not in", values, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("type_id between", value1, value2, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("type_id not between", value1, value2, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNull() {
            addCriterion("type_name is null");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNotNull() {
            addCriterion("type_name is not null");
            return (Criteria) this;
        }

        public Criteria andTypeNameEqualTo(String value) {
            addCriterion("type_name =", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotEqualTo(String value) {
            addCriterion("type_name <>", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThan(String value) {
            addCriterion("type_name >", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("type_name >=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThan(String value) {
            addCriterion("type_name <", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThanOrEqualTo(String value) {
            addCriterion("type_name <=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLike(String value) {
            addCriterion("type_name like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotLike(String value) {
            addCriterion("type_name not like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameIn(List<String> values) {
            addCriterion("type_name in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotIn(List<String> values) {
            addCriterion("type_name not in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameBetween(String value1, String value2) {
            addCriterion("type_name between", value1, value2, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotBetween(String value1, String value2) {
            addCriterion("type_name not between", value1, value2, "typeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdIsNull() {
            addCriterion("first_type_id is null");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdIsNotNull() {
            addCriterion("first_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdEqualTo(Integer value) {
            addCriterion("first_type_id =", value, "firstTypeId");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdNotEqualTo(Integer value) {
            addCriterion("first_type_id <>", value, "firstTypeId");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdGreaterThan(Integer value) {
            addCriterion("first_type_id >", value, "firstTypeId");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("first_type_id >=", value, "firstTypeId");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdLessThan(Integer value) {
            addCriterion("first_type_id <", value, "firstTypeId");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("first_type_id <=", value, "firstTypeId");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdIn(List<Integer> values) {
            addCriterion("first_type_id in", values, "firstTypeId");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdNotIn(List<Integer> values) {
            addCriterion("first_type_id not in", values, "firstTypeId");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("first_type_id between", value1, value2, "firstTypeId");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("first_type_id not between", value1, value2, "firstTypeId");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameIsNull() {
            addCriterion("first_type_name is null");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameIsNotNull() {
            addCriterion("first_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameEqualTo(String value) {
            addCriterion("first_type_name =", value, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameNotEqualTo(String value) {
            addCriterion("first_type_name <>", value, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameGreaterThan(String value) {
            addCriterion("first_type_name >", value, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("first_type_name >=", value, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameLessThan(String value) {
            addCriterion("first_type_name <", value, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameLessThanOrEqualTo(String value) {
            addCriterion("first_type_name <=", value, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameLike(String value) {
            addCriterion("first_type_name like", value, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameNotLike(String value) {
            addCriterion("first_type_name not like", value, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameIn(List<String> values) {
            addCriterion("first_type_name in", values, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameNotIn(List<String> values) {
            addCriterion("first_type_name not in", values, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameBetween(String value1, String value2) {
            addCriterion("first_type_name between", value1, value2, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameNotBetween(String value1, String value2) {
            addCriterion("first_type_name not between", value1, value2, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdIsNull() {
            addCriterion("second_type_id is null");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdIsNotNull() {
            addCriterion("second_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdEqualTo(Integer value) {
            addCriterion("second_type_id =", value, "secondTypeId");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdNotEqualTo(Integer value) {
            addCriterion("second_type_id <>", value, "secondTypeId");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdGreaterThan(Integer value) {
            addCriterion("second_type_id >", value, "secondTypeId");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("second_type_id >=", value, "secondTypeId");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdLessThan(Integer value) {
            addCriterion("second_type_id <", value, "secondTypeId");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("second_type_id <=", value, "secondTypeId");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdIn(List<Integer> values) {
            addCriterion("second_type_id in", values, "secondTypeId");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdNotIn(List<Integer> values) {
            addCriterion("second_type_id not in", values, "secondTypeId");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("second_type_id between", value1, value2, "secondTypeId");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("second_type_id not between", value1, value2, "secondTypeId");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameIsNull() {
            addCriterion("second_type_name is null");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameIsNotNull() {
            addCriterion("second_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameEqualTo(String value) {
            addCriterion("second_type_name =", value, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameNotEqualTo(String value) {
            addCriterion("second_type_name <>", value, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameGreaterThan(String value) {
            addCriterion("second_type_name >", value, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("second_type_name >=", value, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameLessThan(String value) {
            addCriterion("second_type_name <", value, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameLessThanOrEqualTo(String value) {
            addCriterion("second_type_name <=", value, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameLike(String value) {
            addCriterion("second_type_name like", value, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameNotLike(String value) {
            addCriterion("second_type_name not like", value, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameIn(List<String> values) {
            addCriterion("second_type_name in", values, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameNotIn(List<String> values) {
            addCriterion("second_type_name not in", values, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameBetween(String value1, String value2) {
            addCriterion("second_type_name between", value1, value2, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameNotBetween(String value1, String value2) {
            addCriterion("second_type_name not between", value1, value2, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andThridTypeIdIsNull() {
            addCriterion("thrid_type_id is null");
            return (Criteria) this;
        }

        public Criteria andThridTypeIdIsNotNull() {
            addCriterion("thrid_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andThridTypeIdEqualTo(Integer value) {
            addCriterion("thrid_type_id =", value, "thridTypeId");
            return (Criteria) this;
        }

        public Criteria andThridTypeIdNotEqualTo(Integer value) {
            addCriterion("thrid_type_id <>", value, "thridTypeId");
            return (Criteria) this;
        }

        public Criteria andThridTypeIdGreaterThan(Integer value) {
            addCriterion("thrid_type_id >", value, "thridTypeId");
            return (Criteria) this;
        }

        public Criteria andThridTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("thrid_type_id >=", value, "thridTypeId");
            return (Criteria) this;
        }

        public Criteria andThridTypeIdLessThan(Integer value) {
            addCriterion("thrid_type_id <", value, "thridTypeId");
            return (Criteria) this;
        }

        public Criteria andThridTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("thrid_type_id <=", value, "thridTypeId");
            return (Criteria) this;
        }

        public Criteria andThridTypeIdIn(List<Integer> values) {
            addCriterion("thrid_type_id in", values, "thridTypeId");
            return (Criteria) this;
        }

        public Criteria andThridTypeIdNotIn(List<Integer> values) {
            addCriterion("thrid_type_id not in", values, "thridTypeId");
            return (Criteria) this;
        }

        public Criteria andThridTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("thrid_type_id between", value1, value2, "thridTypeId");
            return (Criteria) this;
        }

        public Criteria andThridTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("thrid_type_id not between", value1, value2, "thridTypeId");
            return (Criteria) this;
        }

        public Criteria andThridTypeNameIsNull() {
            addCriterion("thrid_type_name is null");
            return (Criteria) this;
        }

        public Criteria andThridTypeNameIsNotNull() {
            addCriterion("thrid_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andThridTypeNameEqualTo(String value) {
            addCriterion("thrid_type_name =", value, "thridTypeName");
            return (Criteria) this;
        }

        public Criteria andThridTypeNameNotEqualTo(String value) {
            addCriterion("thrid_type_name <>", value, "thridTypeName");
            return (Criteria) this;
        }

        public Criteria andThridTypeNameGreaterThan(String value) {
            addCriterion("thrid_type_name >", value, "thridTypeName");
            return (Criteria) this;
        }

        public Criteria andThridTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("thrid_type_name >=", value, "thridTypeName");
            return (Criteria) this;
        }

        public Criteria andThridTypeNameLessThan(String value) {
            addCriterion("thrid_type_name <", value, "thridTypeName");
            return (Criteria) this;
        }

        public Criteria andThridTypeNameLessThanOrEqualTo(String value) {
            addCriterion("thrid_type_name <=", value, "thridTypeName");
            return (Criteria) this;
        }

        public Criteria andThridTypeNameLike(String value) {
            addCriterion("thrid_type_name like", value, "thridTypeName");
            return (Criteria) this;
        }

        public Criteria andThridTypeNameNotLike(String value) {
            addCriterion("thrid_type_name not like", value, "thridTypeName");
            return (Criteria) this;
        }

        public Criteria andThridTypeNameIn(List<String> values) {
            addCriterion("thrid_type_name in", values, "thridTypeName");
            return (Criteria) this;
        }

        public Criteria andThridTypeNameNotIn(List<String> values) {
            addCriterion("thrid_type_name not in", values, "thridTypeName");
            return (Criteria) this;
        }

        public Criteria andThridTypeNameBetween(String value1, String value2) {
            addCriterion("thrid_type_name between", value1, value2, "thridTypeName");
            return (Criteria) this;
        }

        public Criteria andThridTypeNameNotBetween(String value1, String value2) {
            addCriterion("thrid_type_name not between", value1, value2, "thridTypeName");
            return (Criteria) this;
        }

        public Criteria andSourceIdIsNull() {
            addCriterion("source_id is null");
            return (Criteria) this;
        }

        public Criteria andSourceIdIsNotNull() {
            addCriterion("source_id is not null");
            return (Criteria) this;
        }

        public Criteria andSourceIdEqualTo(Integer value) {
            addCriterion("source_id =", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdNotEqualTo(Integer value) {
            addCriterion("source_id <>", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdGreaterThan(Integer value) {
            addCriterion("source_id >", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("source_id >=", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdLessThan(Integer value) {
            addCriterion("source_id <", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdLessThanOrEqualTo(Integer value) {
            addCriterion("source_id <=", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdIn(List<Integer> values) {
            addCriterion("source_id in", values, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdNotIn(List<Integer> values) {
            addCriterion("source_id not in", values, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdBetween(Integer value1, Integer value2) {
            addCriterion("source_id between", value1, value2, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("source_id not between", value1, value2, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceNameIsNull() {
            addCriterion("source_name is null");
            return (Criteria) this;
        }

        public Criteria andSourceNameIsNotNull() {
            addCriterion("source_name is not null");
            return (Criteria) this;
        }

        public Criteria andSourceNameEqualTo(String value) {
            addCriterion("source_name =", value, "sourceName");
            return (Criteria) this;
        }

        public Criteria andSourceNameNotEqualTo(String value) {
            addCriterion("source_name <>", value, "sourceName");
            return (Criteria) this;
        }

        public Criteria andSourceNameGreaterThan(String value) {
            addCriterion("source_name >", value, "sourceName");
            return (Criteria) this;
        }

        public Criteria andSourceNameGreaterThanOrEqualTo(String value) {
            addCriterion("source_name >=", value, "sourceName");
            return (Criteria) this;
        }

        public Criteria andSourceNameLessThan(String value) {
            addCriterion("source_name <", value, "sourceName");
            return (Criteria) this;
        }

        public Criteria andSourceNameLessThanOrEqualTo(String value) {
            addCriterion("source_name <=", value, "sourceName");
            return (Criteria) this;
        }

        public Criteria andSourceNameLike(String value) {
            addCriterion("source_name like", value, "sourceName");
            return (Criteria) this;
        }

        public Criteria andSourceNameNotLike(String value) {
            addCriterion("source_name not like", value, "sourceName");
            return (Criteria) this;
        }

        public Criteria andSourceNameIn(List<String> values) {
            addCriterion("source_name in", values, "sourceName");
            return (Criteria) this;
        }

        public Criteria andSourceNameNotIn(List<String> values) {
            addCriterion("source_name not in", values, "sourceName");
            return (Criteria) this;
        }

        public Criteria andSourceNameBetween(String value1, String value2) {
            addCriterion("source_name between", value1, value2, "sourceName");
            return (Criteria) this;
        }

        public Criteria andSourceNameNotBetween(String value1, String value2) {
            addCriterion("source_name not between", value1, value2, "sourceName");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andClassIdIsNull() {
            addCriterion("class_id is null");
            return (Criteria) this;
        }

        public Criteria andClassIdIsNotNull() {
            addCriterion("class_id is not null");
            return (Criteria) this;
        }

        public Criteria andClassIdEqualTo(String value) {
            addCriterion("class_id =", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotEqualTo(String value) {
            addCriterion("class_id <>", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThan(String value) {
            addCriterion("class_id >", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThanOrEqualTo(String value) {
            addCriterion("class_id >=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThan(String value) {
            addCriterion("class_id <", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThanOrEqualTo(String value) {
            addCriterion("class_id <=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLike(String value) {
            addCriterion("class_id like", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotLike(String value) {
            addCriterion("class_id not like", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdIn(List<String> values) {
            addCriterion("class_id in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotIn(List<String> values) {
            addCriterion("class_id not in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdBetween(String value1, String value2) {
            addCriterion("class_id between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotBetween(String value1, String value2) {
            addCriterion("class_id not between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andLocationIsNull() {
            addCriterion("location is null");
            return (Criteria) this;
        }

        public Criteria andLocationIsNotNull() {
            addCriterion("location is not null");
            return (Criteria) this;
        }

        public Criteria andLocationEqualTo(String value) {
            addCriterion("location =", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotEqualTo(String value) {
            addCriterion("location <>", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThan(String value) {
            addCriterion("location >", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThanOrEqualTo(String value) {
            addCriterion("location >=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThan(String value) {
            addCriterion("location <", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThanOrEqualTo(String value) {
            addCriterion("location <=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLike(String value) {
            addCriterion("location like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotLike(String value) {
            addCriterion("location not like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationIn(List<String> values) {
            addCriterion("location in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotIn(List<String> values) {
            addCriterion("location not in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationBetween(String value1, String value2) {
            addCriterion("location between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotBetween(String value1, String value2) {
            addCriterion("location not between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andLiveRoomIsNull() {
            addCriterion("live_room is null");
            return (Criteria) this;
        }

        public Criteria andLiveRoomIsNotNull() {
            addCriterion("live_room is not null");
            return (Criteria) this;
        }

        public Criteria andLiveRoomEqualTo(String value) {
            addCriterion("live_room =", value, "liveRoom");
            return (Criteria) this;
        }

        public Criteria andLiveRoomNotEqualTo(String value) {
            addCriterion("live_room <>", value, "liveRoom");
            return (Criteria) this;
        }

        public Criteria andLiveRoomGreaterThan(String value) {
            addCriterion("live_room >", value, "liveRoom");
            return (Criteria) this;
        }

        public Criteria andLiveRoomGreaterThanOrEqualTo(String value) {
            addCriterion("live_room >=", value, "liveRoom");
            return (Criteria) this;
        }

        public Criteria andLiveRoomLessThan(String value) {
            addCriterion("live_room <", value, "liveRoom");
            return (Criteria) this;
        }

        public Criteria andLiveRoomLessThanOrEqualTo(String value) {
            addCriterion("live_room <=", value, "liveRoom");
            return (Criteria) this;
        }

        public Criteria andLiveRoomLike(String value) {
            addCriterion("live_room like", value, "liveRoom");
            return (Criteria) this;
        }

        public Criteria andLiveRoomNotLike(String value) {
            addCriterion("live_room not like", value, "liveRoom");
            return (Criteria) this;
        }

        public Criteria andLiveRoomIn(List<String> values) {
            addCriterion("live_room in", values, "liveRoom");
            return (Criteria) this;
        }

        public Criteria andLiveRoomNotIn(List<String> values) {
            addCriterion("live_room not in", values, "liveRoom");
            return (Criteria) this;
        }

        public Criteria andLiveRoomBetween(String value1, String value2) {
            addCriterion("live_room between", value1, value2, "liveRoom");
            return (Criteria) this;
        }

        public Criteria andLiveRoomNotBetween(String value1, String value2) {
            addCriterion("live_room not between", value1, value2, "liveRoom");
            return (Criteria) this;
        }

        public Criteria andResolvorIsNull() {
            addCriterion("resolvor is null");
            return (Criteria) this;
        }

        public Criteria andResolvorIsNotNull() {
            addCriterion("resolvor is not null");
            return (Criteria) this;
        }

        public Criteria andResolvorEqualTo(String value) {
            addCriterion("resolvor =", value, "resolvor");
            return (Criteria) this;
        }

        public Criteria andResolvorNotEqualTo(String value) {
            addCriterion("resolvor <>", value, "resolvor");
            return (Criteria) this;
        }

        public Criteria andResolvorGreaterThan(String value) {
            addCriterion("resolvor >", value, "resolvor");
            return (Criteria) this;
        }

        public Criteria andResolvorGreaterThanOrEqualTo(String value) {
            addCriterion("resolvor >=", value, "resolvor");
            return (Criteria) this;
        }

        public Criteria andResolvorLessThan(String value) {
            addCriterion("resolvor <", value, "resolvor");
            return (Criteria) this;
        }

        public Criteria andResolvorLessThanOrEqualTo(String value) {
            addCriterion("resolvor <=", value, "resolvor");
            return (Criteria) this;
        }

        public Criteria andResolvorLike(String value) {
            addCriterion("resolvor like", value, "resolvor");
            return (Criteria) this;
        }

        public Criteria andResolvorNotLike(String value) {
            addCriterion("resolvor not like", value, "resolvor");
            return (Criteria) this;
        }

        public Criteria andResolvorIn(List<String> values) {
            addCriterion("resolvor in", values, "resolvor");
            return (Criteria) this;
        }

        public Criteria andResolvorNotIn(List<String> values) {
            addCriterion("resolvor not in", values, "resolvor");
            return (Criteria) this;
        }

        public Criteria andResolvorBetween(String value1, String value2) {
            addCriterion("resolvor between", value1, value2, "resolvor");
            return (Criteria) this;
        }

        public Criteria andResolvorNotBetween(String value1, String value2) {
            addCriterion("resolvor not between", value1, value2, "resolvor");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table question_detail
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table question_detail
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}