package com.deal.mrzhang.deal.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table question_source
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class QuestionSource implements Serializable {
    /**
     * Database Column Remarks:
     *   问题来源途径id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_source.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   问题来源名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_source.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question_source
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_source.id
     *
     * @return the value of question_source.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_source.id
     *
     * @param id the value for question_source.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_source.name
     *
     * @return the value of question_source.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_source.name
     *
     * @param name the value for question_source.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }
}