package com.deal.mrzhang.deal.entity;

import java.util.ArrayList;
import java.util.List;

public class SecondQuestionTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    public SecondQuestionTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSecondTypeIdIsNull() {
            addCriterion("second_type_id is null");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdIsNotNull() {
            addCriterion("second_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdEqualTo(Integer value) {
            addCriterion("second_type_id =", value, "secondTypeId");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdNotEqualTo(Integer value) {
            addCriterion("second_type_id <>", value, "secondTypeId");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdGreaterThan(Integer value) {
            addCriterion("second_type_id >", value, "secondTypeId");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("second_type_id >=", value, "secondTypeId");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdLessThan(Integer value) {
            addCriterion("second_type_id <", value, "secondTypeId");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("second_type_id <=", value, "secondTypeId");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdIn(List<Integer> values) {
            addCriterion("second_type_id in", values, "secondTypeId");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdNotIn(List<Integer> values) {
            addCriterion("second_type_id not in", values, "secondTypeId");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("second_type_id between", value1, value2, "secondTypeId");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("second_type_id not between", value1, value2, "secondTypeId");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameIsNull() {
            addCriterion("second_type_name is null");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameIsNotNull() {
            addCriterion("second_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameEqualTo(String value) {
            addCriterion("second_type_name =", value, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameNotEqualTo(String value) {
            addCriterion("second_type_name <>", value, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameGreaterThan(String value) {
            addCriterion("second_type_name >", value, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("second_type_name >=", value, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameLessThan(String value) {
            addCriterion("second_type_name <", value, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameLessThanOrEqualTo(String value) {
            addCriterion("second_type_name <=", value, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameLike(String value) {
            addCriterion("second_type_name like", value, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameNotLike(String value) {
            addCriterion("second_type_name not like", value, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameIn(List<String> values) {
            addCriterion("second_type_name in", values, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameNotIn(List<String> values) {
            addCriterion("second_type_name not in", values, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameBetween(String value1, String value2) {
            addCriterion("second_type_name between", value1, value2, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNameNotBetween(String value1, String value2) {
            addCriterion("second_type_name not between", value1, value2, "secondTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdIsNull() {
            addCriterion("first_type_id is null");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdIsNotNull() {
            addCriterion("first_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdEqualTo(Integer value) {
            addCriterion("first_type_id =", value, "firstTypeId");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdNotEqualTo(Integer value) {
            addCriterion("first_type_id <>", value, "firstTypeId");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdGreaterThan(Integer value) {
            addCriterion("first_type_id >", value, "firstTypeId");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("first_type_id >=", value, "firstTypeId");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdLessThan(Integer value) {
            addCriterion("first_type_id <", value, "firstTypeId");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("first_type_id <=", value, "firstTypeId");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdIn(List<Integer> values) {
            addCriterion("first_type_id in", values, "firstTypeId");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdNotIn(List<Integer> values) {
            addCriterion("first_type_id not in", values, "firstTypeId");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("first_type_id between", value1, value2, "firstTypeId");
            return (Criteria) this;
        }

        public Criteria andFirstTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("first_type_id not between", value1, value2, "firstTypeId");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameIsNull() {
            addCriterion("first_type_name is null");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameIsNotNull() {
            addCriterion("first_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameEqualTo(String value) {
            addCriterion("first_type_name =", value, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameNotEqualTo(String value) {
            addCriterion("first_type_name <>", value, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameGreaterThan(String value) {
            addCriterion("first_type_name >", value, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("first_type_name >=", value, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameLessThan(String value) {
            addCriterion("first_type_name <", value, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameLessThanOrEqualTo(String value) {
            addCriterion("first_type_name <=", value, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameLike(String value) {
            addCriterion("first_type_name like", value, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameNotLike(String value) {
            addCriterion("first_type_name not like", value, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameIn(List<String> values) {
            addCriterion("first_type_name in", values, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameNotIn(List<String> values) {
            addCriterion("first_type_name not in", values, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameBetween(String value1, String value2) {
            addCriterion("first_type_name between", value1, value2, "firstTypeName");
            return (Criteria) this;
        }

        public Criteria andFirstTypeNameNotBetween(String value1, String value2) {
            addCriterion("first_type_name not between", value1, value2, "firstTypeName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table second_question_type
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}