package com.deal.mrzhang.deal.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table thrid_question_type
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ThridQuestionType implements Serializable {
    /**
     * Database Column Remarks:
     *   三级问题问题类型id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thrid_question_type.question_type_id
     *
     * @mbg.generated
     */
    private Integer questionTypeId;

    /**
     * Database Column Remarks:
     *   三级问题类型id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thrid_question_type.question_type_name
     *
     * @mbg.generated
     */
    private String questionTypeName;

    /**
     * Database Column Remarks:
     *   二级问题类型id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thrid_question_type.second_type_id
     *
     * @mbg.generated
     */
    private Integer secondTypeId;

    /**
     * Database Column Remarks:
     *   二级问题类型名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thrid_question_type.second_type_name
     *
     * @mbg.generated
     */
    private String secondTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table thrid_question_type
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thrid_question_type.question_type_id
     *
     * @return the value of thrid_question_type.question_type_id
     *
     * @mbg.generated
     */
    public Integer getQuestionTypeId() {
        return questionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thrid_question_type.question_type_id
     *
     * @param questionTypeId the value for thrid_question_type.question_type_id
     *
     * @mbg.generated
     */
    public void setQuestionTypeId(Integer questionTypeId) {
        this.questionTypeId = questionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thrid_question_type.question_type_name
     *
     * @return the value of thrid_question_type.question_type_name
     *
     * @mbg.generated
     */
    public String getQuestionTypeName() {
        return questionTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thrid_question_type.question_type_name
     *
     * @param questionTypeName the value for thrid_question_type.question_type_name
     *
     * @mbg.generated
     */
    public void setQuestionTypeName(String questionTypeName) {
        this.questionTypeName = questionTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thrid_question_type.second_type_id
     *
     * @return the value of thrid_question_type.second_type_id
     *
     * @mbg.generated
     */
    public Integer getSecondTypeId() {
        return secondTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thrid_question_type.second_type_id
     *
     * @param secondTypeId the value for thrid_question_type.second_type_id
     *
     * @mbg.generated
     */
    public void setSecondTypeId(Integer secondTypeId) {
        this.secondTypeId = secondTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thrid_question_type.second_type_name
     *
     * @return the value of thrid_question_type.second_type_name
     *
     * @mbg.generated
     */
    public String getSecondTypeName() {
        return secondTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thrid_question_type.second_type_name
     *
     * @param secondTypeName the value for thrid_question_type.second_type_name
     *
     * @mbg.generated
     */
    public void setSecondTypeName(String secondTypeName) {
        this.secondTypeName = secondTypeName;
    }
}