spring:
  application:
    name: deal
  datasource:
    username: root
    password: Mrzhang1@
    url: jdbc:mysql://119.96.124.154:3306/deal?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 60000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      pool-prepared-statements: true
      filters: stat,wall,log4j,config
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000



server:
  port: 8081
  servlet:
    context-path: /deal/
swagger:
  enable: true
### mybatis config ###
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.deal.mrzhang.deal.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com:
      deal:
        mrzhang:
          deal:
            mapper: DEBUG
log4j:
  rootCategory: INFO,stdout,jdbc