package com.deal.mrzhang.deal.mapper;

import com.deal.mrzhang.deal.entity.FirstQuestionType;
import com.deal.mrzhang.deal.entity.FirstQuestionTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FirstQuestionTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_question_type
     *
     * @mbg.generated
     */
    long countByExample(FirstQuestionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_question_type
     *
     * @mbg.generated
     */
    int deleteByExample(FirstQuestionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_question_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer questionTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_question_type
     *
     * @mbg.generated
     */
    int insert(FirstQuestionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_question_type
     *
     * @mbg.generated
     */
    int insertSelective(FirstQuestionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_question_type
     *
     * @mbg.generated
     */
    List<FirstQuestionType> selectByExample(FirstQuestionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_question_type
     *
     * @mbg.generated
     */
    FirstQuestionType selectByPrimaryKey(Integer questionTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_question_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FirstQuestionType record, @Param("example") FirstQuestionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_question_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FirstQuestionType record, @Param("example") FirstQuestionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_question_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FirstQuestionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_question_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FirstQuestionType record);
}