package com.deal.mrzhang.deal.mapper;

import com.deal.mrzhang.deal.entity.QuestionSource;
import com.deal.mrzhang.deal.entity.QuestionSourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuestionSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_source
     *
     * @mbg.generated
     */
    long countByExample(QuestionSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_source
     *
     * @mbg.generated
     */
    int deleteByExample(QuestionSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_source
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_source
     *
     * @mbg.generated
     */
    int insert(QuestionSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_source
     *
     * @mbg.generated
     */
    int insertSelective(QuestionSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_source
     *
     * @mbg.generated
     */
    List<QuestionSource> selectByExample(QuestionSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_source
     *
     * @mbg.generated
     */
    QuestionSource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_source
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QuestionSource record, @Param("example") QuestionSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_source
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QuestionSource record, @Param("example") QuestionSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_source
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QuestionSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_source
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QuestionSource record);
}