package com.deal.mrzhang.deal.mapper;

import com.deal.mrzhang.deal.entity.SecondQuestionType;
import com.deal.mrzhang.deal.entity.SecondQuestionTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecondQuestionTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    long countByExample(SecondQuestionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    int deleteByExample(SecondQuestionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer secondTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    int insert(SecondQuestionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    int insertSelective(SecondQuestionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    List<SecondQuestionType> selectByExample(SecondQuestionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    SecondQuestionType selectByPrimaryKey(Integer secondTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SecondQuestionType record, @Param("example") SecondQuestionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SecondQuestionType record, @Param("example") SecondQuestionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SecondQuestionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_question_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SecondQuestionType record);
}